import { COMMAND_CODES } from '../../shared/protocol';
import { send } from './transmitter';

/**
 * App→server presence beat.
 *
 * The *car's* keep-alive is now generated by the bridge server
 * (node_server/src/server.ts) on Node's reliable event loop, so a stalled RN JS
 * thread can no longer starve it and false-trip the car's ~300ms safety stop —
 * that stall was the bug (see [[feature-arduino-drive-diagnosis]]). This beat's
 * only job is to tell the server the app is still alive and in control: the
 * server treats any inbound message as "present", so we send a lightweight 'kp'
 * at a relaxed cadence the JS thread holds easily.
 *
 * If this beat stops (app suspended/killed) the server stops the car within its
 * presence timeout (~2s); a real transport loss (Wi-Fi drop) is caught faster
 * by the server's WS ping/pong. The 250ms cadence leaves wide margin under that
 * 2s window, so ordinary JS-thread jank never trips a false stop — unlike the
 * old 100ms beat, which had to win a hard 300ms race on the JS thread.
 */
const PRESENCE_INTERVAL_MS = 250;

let timer: ReturnType<typeof setInterval> | null = null;

export function start(): void {
  if (timer) {
    return;
  }
  timer = setInterval(() => send(COMMAND_CODES.KEEP_ALIVE), PRESENCE_INTERVAL_MS);
}

export function stop(): void {
  if (timer) {
    clearInterval(timer);
    timer = null;
  }
}

export default { start, stop };
